# Generated by Django 3.1.6 on 2021-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0001_initial'),
        ('accounts', '0003_auto_20210207_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Receptionist.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.ManyToManyField(blank=True, null=True, to='Receptionist.Degree'),
        ),
    ]
